# Generated by Django 5.0.4 on 2024-07-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0002_produits_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produit/'),
        ),
    ]
